services:
  app1:
    image: busybox
    container_name: bai14_app1
    command: sh -c "while true; do echo app1 running; sleep 10; done"
    networks:
      - private_net

  app2:
    image: busybox
    container_name: bai14_app2
    command: sh -c "while true; do echo app2 running; sleep 10; done"
    networks:
      - private_net

networks:
  private_net:
    driver: bridge